[project]
name = "flyingduck-mcp"
version = "1.0.0"
description = "Flyingduck-MCP Security Scanner CLI"
authors = [{name = "Your Name", email = "your@email.com"}]
dependencies = [
    "typer>=0.9.0",
    "rich>=13.0.0",
    "pyyaml>=6.0"
]

[project.scripts]
flyingduck = "flyingduck_mcp.cli:app" 